### ISSUE TITLE
tamuclock discriminates against weekdays [feature request]

### ISSUE THREAD

**Issue by jeff-hykin** [rsrickshaw/tamuclock#2]
![screen shot 2018-07-05 at 1 02 39 pm](https://user-images.githubusercontent.com/17692058/42339842-dbb99788-8053-11e8-9b17-7fbc473e35c8.png)

I have a class that considers its activity day as MTWTF, but I'm forced to pick a specific weekday

**Comment by rsrickshaw** [comment]
Implemented.
